server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/extra_db?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    #hibernate:
      #ddl-auto: create-drop


  servlet:
    multipart:
      max-file-size: 4096KB
      max-request-size: 4096KB
  freemarker:
    cache: false
    content-type: text/html
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates/page
    settings: {'locale':'zh_CN','date_format':'yyyy-MM-dd','time_format':'HH:mm:ss','datetime_format':'yyyy-MM-dd HH:mm:ss'}

# 设置文件处理这, 支持多个, 使用英文逗号分隔。如 DiskFileHelper,QiNiuFileHelper
handle:
  file:
    helper: DiskFileHelper
disk:
  file:
    path: F:/tmp


pageoffice:
  reg:
    sysPath: F:/tmp/lic
    poServerUrl: /poserver.zz
    poSetup: /posetup.exe
    pageofficeJs: /pageoffice.js
    jqueryUrl: /jquery.min.js
    pobstyleCssUrl: /pobstyle.css
    sealSetup: /sealsetup.exe

    adminPassword: 111111
    adminSeal: /adminseal.zz
    sealImage: /sealimage.zz
    loginSeal: /loginseal.zz




